# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a062307392cac440bfb973273b2060afde03e4ffe6bfe5cf4b9558e033ec7fab5812504c6051d6d65830737a2907c7b36db7f4dfb6034de3b295fa881cb941fd

test:
  secret_key_base: 606e023587d0a1af15e4bb37de8539cf0fc2d286d0d665ad411b0275a5af71932105bbf9da1fc909eaacccdb0976389094234fae40d0daa6be0894afbf606487

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
